# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'JRTForm' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JRTForm
  pod 'libPhoneNumber-iOS'

  target 'JRTFormTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
